server:
  port: 8888
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/altraman00/alkb-cloud-config.git
          username: 869118563@qq.com
          password: xxxxxx

# 指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
  instance:
    hostname: localhost