#spring:
#  influx:
#    url: http://10.27.0.47:8087 #influxdb服务器的地址
#    user: mobvoi #用户名
#    password: 123456789 #密码
#    database: mydb #指定的数据库
#    retentionPolicy: default

#spring:
#  influx:
#    url: http://10.27.0.44:8086 #influxdb服务器的地址
#    user: root #用户名
#    password: 123456 #密码
#    database: my_sensor1 #指定的数据库
#    retentionPolicy: autogen


spring:
  influx:
    url: http://10.27.0.147:8086 #influxdb服务器的地址
    user: mobvoi #用户名
    password: 123456 #密码
    database: ticwatch #指定的数据库
    retentionPolicy: autogen

