server:
  port: 8080

spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/alkb-cloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
  flyway:
    enabled: true
    encoding: utf-8
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true
    validate-on-migrate: false