version: '2'
services:
  mysql:
    image: 'mysql/mysql-server:5.6.35'
    restart: always
    container_name: mysql
    network_mode: "host"
    environment:
        MYSQL_ROOT_PASSWORD: "123456"
        MYSQL_USER: 'test'
        MYSQL_PASS: '123456'
    volumes:
        - "./db:/var/lib/mysql"
        - "./conf/my.cnf:/etc/my.cnf"
        - "./init:/docker-entrypoint-initdb.d/"
    ports:
        - "3306:3306"
