#server:
#  port: 8080
#spring:
#  resources:
#    static-locations: /static
#  thymeleaf:
#    cache: false # 开发时关闭缓存,不然没法看到实时页面
#    mode: HTML # 用非严格的 HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mcloud?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    jpa:
#      show-sql: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    #    password: 123456
#    timeout: 5000
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#  servlet:
#    multipart:
#      max-request-size: 50MB # 设置单个文件大小
#      max-file-size: 50MB # 设置单次请求文件的总大小
#
#file:
#  basepath: /Users/knight/Desktop/mobvoi/pic/
#
#yakir:
#  upload:
#    dir: /Users/knight/Desktop/mobvoi/pic/
#    chunkSize: 5242880
#
##yakir:
##  upload:
##    dir: /Users/knight/Desktop/mobvoi/pic/
##    #1024*1024=1 048 576,5M=5 242 880
##    chunkSize: 5 242 880
