version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    volumes:
      - /opt/graylog/data/db:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - /opt/graylog/data/es/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    ports:
      - 9202:9200
      - 9302:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.6-1
    volumes:
      - /opt/graylog/data/graylog_journal:/usr/share/graylog/data/journal
      - /opt/graylog/config:/usr/share/graylog/data/config
      - /etc/localtime:/etc/localtime
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=Fi12RswEAAbZfzXiEfJNeaoaBDZarJczJiM8CIObJLLig8Im6vyX5xJZCgO5dmvUVXQmv2RRXXtYR9dLDpxBx1JctAJGyn0L
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
      - GRAYLOG_WEB_ENDPOINT_URI=http://log.supplus.cn/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # input tcp 
      - 5044:5044
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
